---

#####
# Apache

- name: Enable Port for HTTP communication in SELinux
  seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: present
  ignore_errors: yes
  with_items:
    - "{{ www_port_ks }}"
    - "{{ www_port_RPMs }}"
    - "{{ www_port_workshopdocs }}"
    - "{{ www_port_workshopfiles }}"
    - "{{ www_port_tower }}"
  tags:
    - hypervisor_setup

- name: Open firewall port for Apache HTTPD
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    zone: public
    state: enabled
  with_items:
    - "{{ www_port_ks }}"
    - "{{ www_port_RPMs }}"
    - "{{ www_port_workshopdocs }}"
    - "{{ www_port_workshopfiles }}"
    - "{{ www_port_tower }}"
  tags:
    - hypervisor_setup

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded
    enabled: yes
  tags:
    - hypervisor_setup

- name: Start Apache HTTPD - Web Service (required for kickstart for network configuration)
  service:
    name: httpd
    state: started
    enabled: yes
  tags:
   - hypervisor_setup

- name: re-Start Apache HTTPD (to ensure latest configuration is loaded)
  service:
    name: httpd
    state: restarted
    enabled: yes
  tags:
    - hypervisor_setup
