---

#####
# Kickstart Web Config

- name: Stage Apache HTTPD kickstart configuration file
  template:
    src: "{{ www_file_configuration_ks_template }}"
    dest: "/etc/httpd/conf.d/{{ www_file_configuration_ks }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - hypervisor_setup

- name: Create kickstart configuration file directory available via web service
  file:
    path: "{{ kickstart_directory }}"
    state: directory
    owner: apache
    group: apache
    mode: 0775
  tags:
    - hypervisor_setup

- name: Stage kickstart configuration file for guest network configuration installations
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: apache
    group: apache
    mode: "a=r"
  with_items:
    - name: node
      src: "{{ kickstart_node_configuration_template }}"
      dest: "{{ kickstart_directory }}/{{ kickstart_node_configuration }}"
    - name: tower
      src: "{{ kickstart_tower_configuration_template }}"
      dest: "{{ kickstart_directory }}/{{ kickstart_tower_configuration }}"

- name: Set SELinux context of kickstart file
  sefcontext:
    target: "{{ item }}"
    setype: httpd_sys_content_t
    state: present
  with_items:
    - "{{ kickstart_directory }}/{{ kickstart_node_configuration }}"
    - "{{ kickstart_directory }}/{{ kickstart_tower_configuration }}"
  ignore_errors: yes

- name: Run restore context to reload SELinux
  shell: "restorecon -Rv {{ kickstart_directory }}"
