---

#####
# Base setup

- name: Install prerequisite RPM packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - gitweb
    - git-daemon
    - httpd
    - libselinux-python
    - libvirt-client
    - libvirt-daemon
    - libvirt-daemon-driver-qemu
    - libvirt-python
    - lorax
    - nfs-utils
    - policycoreutils-python
    - python-lxml
    - qemu-img
    - qemu-kvm
    - qemu-kvm-common
    - qemu-kvm-tools
    - rpcbind
    - samba
    - virt-install
    - virt-manager
  tags:
    - hypervisor_setup

#####
# Kickstart Web Config

- include: kickstart.yml

#####
# Share directory

- name: Create share directory to export deliverables to end-user
  file:
    path: "{{ share_directory }}"
    state: directory
    owner: nobody
    group: nobody
    mode: 0775
  tags:
    - hypervisor_setup

#####
# Ansible Tower

- name: Create Ansible Tower Bundle directory
  file:
    path: "{{ share_directory }}/ansible"
    state: directory
    owner: nobody
    group: nobody
    mode: 0775
  tags:
    - hypervisor_setup

- name: Ensure Ansible Tower is staged
  stat:
    path: "{{ share_directory }}/{{ ansible_tower_bundle_file }}"
  register: ansible_tower_download

- name: Download Ansible Tower Bundle
  get_url:
    url: "{{ ansible_tower_bundle_base_url }}/{{ ansible_tower_bundle_file }}"
    dest: "{{ share_directory }}/{{ ansible_tower_bundle_file }}"
  when: ansible_tower_download.stat.exists == False

- name: UnTar Ansible Tower Bundle
  unarchive:
    remote_src: yes
    src: "{{ share_directory }}/{{ ansible_tower_bundle_file }}"
    dest: "{{ share_directory }}/ansible"
    extra_opts: "--strip-components=1"

#####
# Git

- include: git.yml

#####
# Apache

- include: apache.yml

#####
# KVM

- include: kvm.yml

#####
# NFS

- include: nfs.yml

#####
# Samba

- include: samba.yml

#####
# SELinux

- name: Set SELinux context of shared directory
  sefcontext:
    target: "{{ share_directory }}(/.*)?"
    setype: samba_share_t
    state: present
  ignore_errors: yes
  tags:
    - hypervisor_setup

- name: Run restore context to reload SELinux
  shell: "restorecon -Rv {{ share_directory }}"
  tags:
    - hypervisor_setup
