---

- name: Install prerequisite RPM packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - gitweb
    - git-daemon
    - httpd
    - libselinux-python
    - libvirt-client
    - libvirt-daemon
    - libvirt-daemon-driver-qemu
    - libvirt-python
    - nfs-utils
    - policycoreutils-python
    - python-lxml
    - qemu-img
    - qemu-kvm
    - qemu-kvm-common
    - qemu-kvm-tools
    - rpcbind
    - samba
    - virt-install
    - virt-manager
  tags:
    - hypervisor_setup
