---

#####
# Base setup

- name: Install prerequisite RPM packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - bind-utils
    - cockpit
    - cockpit-dashboard
    - cockpit-shell
    - cockpit-system
    - cockpit-ws
    - coreutils
    - createrepo
    - git
    - gitweb
    - git-daemon
    - httpd
    - libguestfs
    - libguestfs-tools
    - libselinux-python
    - libvirt-client
    - libvirt-daemon
    - libvirt-daemon-driver-qemu
    - libvirt-python
    - lorax
    - nfs-utils
    - policycoreutils-python
    - python-lxml
    - qemu-img
    - qemu-kvm
    - qemu-kvm-common
    - qemu-kvm-tools
    - rpcbind
    - samba
    - sed
    - socat
    - virt-install
    - virt-manager
    - virt-viewer
    - xauth
    - yum-utils
  tags:
    - download
    - hypervisor_setup

#####
# Apache

- include: apache.yml

#####
# Kickstart Web Config

- include: kickstart.yml

#####
# Share directory

- name: Create share directory to export deliverables to end-user
  file:
    path: "{{ share_directory }}"
    state: directory
    owner: nobody
    group: nobody
    mode: 0775
  tags:
    - hypervisor_setup
    - download

#####
# Ansible Tower

- name: Create Ansible Tower Bundle directory
  file:
    path: "{{ share_directory }}/ansible"
    state: directory
    owner: nobody
    group: nobody
    mode: 0775
  tags:
    - hypervisor_setup
    - download

- name: Ensure Ansible Tower is staged
  stat:
    path: "{{ share_directory }}/{{ ansible_tower_bundle_file }}"
  register: ansible_tower_download
  tags:
    - download

- name: Download Ansible Tower Bundle
  get_url:
    url: "{{ ansible_tower_bundle_base_url }}/{{ ansible_tower_bundle_file }}"
    dest: "{{ share_directory }}/{{ ansible_tower_bundle_file }}"
  when: ansible_tower_download.stat.exists == False
  tags:
    - download

- name: UnTar Ansible Tower Bundle
  unarchive:
    remote_src: yes
    src: "{{ share_directory }}/{{ ansible_tower_bundle_file }}"
    dest: "{{ share_directory }}/ansible"
    extra_opts: "--strip-components=1"
  tags:
    - download

- name: Copy Ansible Tower Bundle to directory
  copy:
    src: "{{ share_directory }}/{{ ansible_tower_bundle_file }}"
    dest: "{{ share_directory }}/ansible"
    owner: apache
    group: apache
    mode: 0644

#####
# RHEL

- include: rhel.yml

#####
# Tower

- include: tower.yml

#####
# Workshop Files

- include: workshop-docs.yml

#####
# Workshop Files

- include: workshop-files.yml

#####
# KVM

- include: kvm.yml

#####
# Git

- include: git.yml

#####
# NFS

- include: nfs.yml

#####
# Samba

- include: samba.yml

#####
# SELinux

- name: Set SELinux context of shared directory
  sefcontext:
    target: "{{ share_directory }}(/.*)?"
    setype: public_content_rw_t
    state: present
    reload: True
  ignore_errors: yes
  tags:
    - hypervisor_setup

- name: Run restore context to reload SELinux
  shell: "restorecon -Rv {{ share_directory }}"
  tags:
    - hypervisor_setup
