---

- name: install required local packages
  yum:
    - name: "{{ item }}"
    - state: latest
  with_items:
    - git
    - gitweb
    - git-daemon
    - httpd
    - libselinux-python
    - libvirt-client
    - libvirt-daemon
    - libvirt-daemon-driver-qemu
    - libvirt-python
    - nfs-utils
    - policycoreutils-python
    - python-lxml
    - qemu-img
    - qemu-kvm
    - qemu-kvm-common
    - qemu-kvm-tools
    - samba
    - vim
    - virt-install
    - virt-manager
